const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};
const PROPERTIES = {
    LOAD: 'PROPERTIES_LOAD',
    LOAD_SUCCESS: 'PROPERTIES_LOAD_SUCCESS',
    LOAD_FAIL: 'PROPERTIES_LOAD_FAIL',
};

const FILEUPLOAD = {
    SET_FILES: 'SET_FILES',
    SET_EXISTED_FILES: 'SET_EXISTED_FILES',
    ADD_FILES: 'ADD_FILES',
};
export { IMAGES , PROPERTIES, FILEUPLOAD };
